### ISSUE TITLE
Does SOAPLite work with periodic/bulk structures?

### ISSUE THREAD

**Issue by bartolsthoorn** [SINGROUP/SOAPLite#4]
How do I make sure the periodic boundary conditions are used? The following fails:

```python
from soaplite import getBasisFunc, get_periodic_soap_locals
from ase.build import bulk

atoms = bulk('NaCl', 'rocksalt', a=5.64)

hpos = [
    [0, 0, 0],
]

n_max = 5
l_max = 5
r_cut = 10.0
my_alphas, my_betas = getBasisFunc(r_cut, n_max)

x = get_periodic_soap_locals(
    atoms,
    hpos,
    my_alphas,
    my_betas,
    rCut=r_cut,
    NradBas=n_max,
    Lmax=l_max,
    crossOver=True
)
```

Traceback:
```
/soaplite/soaplite.py:49: RuntimeWarning: divide by zero encountered in true_divide
  cell_images = np.ceil(rCutHard/xyz_arr)
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    crossOver=True
  File "/home/bart/anaconda3/lib/python3.6/site-packages/soaplite-0.9.14-py3.6-linux-x86_64.egg/soaplite/soaplite.py", line 181, in get_periodic_soap_locals
    suce = _get_supercell(obj, rCut)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/soaplite-0.9.14-py3.6-linux-x86_64.egg/soaplite/soaplite.py", line 50, in _get_supercell
    nx = int(cell_images[0])
OverflowError: cannot convert float infinity to integer
```

**Comment by Aki78** [comment]
Thank you for the bug report,
We will fix it by next week.

**Comment by bartolsthoorn** [comment]
OK thank you.

**Comment by marchunter** [comment]
The creation of soap from periodic structures was tested for orthorhombic cells. It is now generalized to arbitrary unit cells. Your code snippet runs fine, let us know if you encounter any other issue.

**Comment by bartolsthoorn** [comment]
Thank you for fixing this!

**Comment by bartolsthoorn** [comment]
Just a sidenote:

I am not sure the supercell logic in this repo is necessary. I think the `ase` library has all of this implemented efficiently already: https://wiki.fysik.dtu.dk/ase/ase/neighborlist.html
